<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="patrones">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="patron">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <!-- Dos caracteres cualquiera (cifras o letras) -->
                            <!-- <xs:pattern value=".." /> -->

                            <!-- Dos cifras -->
                            <!-- <xs:pattern value="\d\d" /> -->

                            <!-- Un carácter cualquiera seguido de una cifra -->
                            <!-- <xs:pattern value=".\d" /> -->

                            <!-- Número de DNI sin letra al final (8 cifras) -->
                            <!-- <xs:pattern value="\d{8}" /> -->

                            <!-- Cualquier combinación de cifras (incluyendo no escribir nada). -->
                            <!-- <xs:pattern value="\d*" /> -->

                            <!-- Cualquier combinación de cifras con, al menos, una cifra. -->
                            <!-- <xs:pattern value="\d+" /> -->

                            <!-- Una letra entre la A y la D seguida de dos cifras (puerta de
                            embarque). -->
                            <!-- <xs:pattern value="[A-D]\d\d" /> -->

                            <!-- Una letra y una o dos cifras (puerta de embarque). -->
                            <!-- <xs:pattern value="[A-D]\d\d?" /> -->

                            <!-- Número de DNI con letra al final (8 cifras y letra). -->
                            <!-- <xs:pattern value="\d{8}[A-Z]" /> -->

                            <!-- Número de DNI con letra al final (8 cifras y letra). -->
                            <!-- <xs:pattern value="\d{8}[A-Za-z]" /> -->

                            <!-- Teléfono con prefijo internacional (el prefijo tiene de 1 a 4
                            cifras, y el teléfono, 9). -->
                            <!-- <xs:pattern value="\d{1,4} \d{9}" /> -->

                            <!-- Teléfono con prefijo internacional (el prefijo tiene de 1 a 4
                            cifras, y el teléfono, 9). Con un formato similar a: +34 971-230-470 -->
                            <xs:pattern value="\+\d{1,4} \d{3}-\d{3}-\d{3}" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>